### ISSUE TITLE
The trained model for Face Verification

### ISSUE THREAD

**Issue by Lacusleng** [sciencefans/Quality-Aware-Network#2]
Is it possible to share the trained model reported in the CVPR 17 paper for unconstrained face recognition?

**Comment by liuyuisanai** [comment]
@Lacusleng Commercial data is used in training face recognition task so I'm afraid we cannot release the final model. However,  since QAN should work on plenty of set-to-set tasks, we encourage researchers to train QAN on different tasks with their own data. For face recognition, there are plenty of databases can be accessed easily such as MS-1M, VGG Face, CASIA, etc..
